### PR TITLE
Builds Improvement

### LINKED ISSUE #175: [BUG] Variety of Builds have typos.
# Bug Report

### Builds requiring Fixes:

- [ ] Mining Active/AFK (Warrior) 100+ (Tempestuous Emotions missing TP)
- [ ] Woodcutter Active/AFK (Mage) 30+ (Inner Peace missing TP)
- [ ] Two Mining / Construction Hybrid (Squire) 100+
- [ ] Catching 100+ (Gilded Sword highlighted instead of Elusive Efficiency)
- [ ] Two Shaman AFK builds (50 & 70)

---

**Details**

OS (e.g. Windows, iOS): Windows
Browser (e.g. Chrome, Safari): Chrome
Idleon Companion Version (see changelog): 0.3.0 (Site Redesign)

### PR DESCRIPTION
**Pull request by 100mars**
# Completed Checklist of updated builds in this PR

## Bug Fixes
#175 
- [x]  Mining Active/AFK (Warrior) 100+ (Tempestuous Emotions missing TP)
- [x]  Woodcutter Active/AFK (Mage) 30+ (Inner Peace missing TP)
- [x]  Two Mining / Construction Hybrid (Squire) 100+
- [x]  Catching 100+ (Gilded Sword highlighted instead of Elusive Efficiency)
- [x]  Two Shaman AFK builds (50 & 70)
- [x]  Two Worship/Choppin Hybrid

## Updated Builds
- [x] Woodcutter Active/AFK (Shaman) 30+ -> 50+, Update build to be for lvl 50 instead.
- [x] Mining Active/AFK (Barb) 30+, -> 50+, Update build to be for lvl 50 instead.
- [x] Mining Active/AFK (Barb) 100+, Fix Talents
- [x] Fishing Active/AFK (Warrior) 30+ -> 50+ 
- [x] Fishing Active/AFK (Warrior) 100+, Fix Talents
- [x] Catching Active/AFK (Bowman) 50+
- [x] Maestro Skilling Build -> Maestro Skilling : Left + Right Hands
- [x] Bowman / Active (~70) #176  (No edit required)
- [x] Hunter Active 50/70/90 should have 360 no scope removed. Remove Eagle Eye as well.

## New Builds

- [x] Mining Active / AFK (Warrior) 30+ , Underneath "warrior" tab, not barbarian.
- [x] Mining Active / AFK (Squire) 50+
- [x] Mining Active / AFK (Squire) 100+
- [x] Woodcutter Active / AFK (Mage) 30+ , Underneath "mage" tab, not shaman.
- [x] Woodcutter Active / AFK (Wizard) 50+
- [x] Catching Active/AFK (Bowman) 50+
- [x] Maestro Skilling (No focus on Left/Right hands)
- [x] Maestro AFK 70+
- [x] Maestro Active 70+
- [x] Maestro Crystal Killer 70+
- [x] Hunter Trapping 70+
- [x] Hunter Trapping 100+

### CODE REVIEW

File: src/data/builds/hunter/5200_hun_trapping_100.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
+import { Class } from "~/composables/Characters";
+
+import { Build } from "~/composables/Builds";
+
+export const build: Build = {
+  title: "Hunter Trapping (~100)",
+  notes: "",
+  version: "1.23",
+  level: 50,
```
Comment (adapap) [inline src/data/builds/hunter/5200_hun_trapping_100.ts:9]: Is the level here correct? The title says ~100, but the leve field says 50. The numeric field might be used in the future to sort/filter builds by level, so I want to make sure these are accurate as we update them.

File: src/data/builds/shaman/2001_2_Alchemy_Choppin_hybrid.ts [hunk 2]
```diff
@@ -4,7 +4,7 @@ import { Build } from "~/composables/Builds";
 
 export const build: Build = {
   title: "Alchemy / Choppin Hybrid (Shaman) 100+",
-  notes: "",
+  notes: " ",
```
Comment (adapap) [inline src/data/builds/shaman/2001_2_Alchemy_Choppin_hybrid.ts:7]: 👀

**Review by adapap — APPROVED** [review]
Other than level field, LGTM!

File: src/data/builds/hunter/5200_hun_trapping_100.ts (hunk 1 above)
Comment (100mars) [reply src/data/builds/hunter/5200_hun_trapping_100.ts:9]: Yep, that's meant to be 100, not 50.

File: src/data/builds/shaman/2001_2_Alchemy_Choppin_hybrid.ts (hunk 2 above)
Comment (100mars) [reply src/data/builds/shaman/2001_2_Alchemy_Choppin_hybrid.ts:7]: I believe this prevents seeing "Notes about your perfect build. Explain the order of upgrades, tradeoffs, or other important notes.

Comment (adapap) [reply src/data/builds/shaman/2001_2_Alchemy_Choppin_hybrid.ts:7]: Ah I guess there's just no build description then because that's the default filler text.
